{{- if .Values.backend.enabled }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "jlpt5.backend.serviceName" . }}
  labels:
    {{- include "jlpt5.backend.labels" . | nindent 4 }}
type: Opaque
stringData:
  DB_PASSWORD: {{ .Values.backend.config.database.password | quote }}
  JWT_SECRET: {{ .Values.backend.config.jwt.secret | quote }}
{{- end }}
