{{- if .Values.postgresql.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "jlpt5.postgresql.serviceName" . }}
  labels:
    {{- include "jlpt5.postgresql.labels" . | nindent 4 }}
spec:
  type: {{ .Values.postgresql.service.type }}
  ports:
    - port: {{ .Values.postgresql.service.port }}
      targetPort: 5432
      protocol: TCP
      name: postgresql
  selector:
    {{- include "jlpt5.postgresql.selectorLabels" . | nindent 4 }}
{{- end }}
